package main

import (
	"bytes"
	"testing"
)

func TestSimple(t *testing.T) {

	pkg := "github.com/mrsinham/zerogen/test/simple"
	structure := "simple"
	write := false
	b := &bytes.Buffer{}
	if err := parsePackage(&pkg, &structure, &write, b); err != nil {
		t.Fatal(err)
	}

	result := `// Code generated by github.com/mrsinham/zerogen. DO NOT EDIT.
package simple

func (s *simple) Reset() {
	s.field1 = 0
	s.field2 = ""
	s.field3 = nil
	s.field4 = [3]int{}
	s.field5 = nil
}
`
	if b.String() != result {
		t.Fatalf("result is not the same as expected : got \n%q \n expected  \n%q	", b.String(), result)
	}

}

func TestComposition(t *testing.T) {

	pkg := "github.com/mrsinham/zerogen/test/composition"
	structure := "composited"
	write := false
	b := &bytes.Buffer{}
	if err := parsePackage(&pkg, &structure, &write, b); err != nil {
		t.Fatal(err)
	}

	result := `// Code generated by github.com/mrsinham/zerogen. DO NOT EDIT.
package composition

func (c *composited) Reset() {
	c.subfield1 = 0
	c.subfield2 = ""
	c.fieldsimple = ""
}
`
	if b.String() != result {
		t.Fatalf("result is not the same as expected : got \n%q \n expected  \n%q", b.String(), result)
	}

}

func TestCompositionExternal(t *testing.T) {

	pkg := "github.com/mrsinham/zerogen/test/compositionexternal"
	structure := "base"
	write := false
	b := &bytes.Buffer{}
	if err := parsePackage(&pkg, &structure, &write, b); err != nil {
		t.Fatal(err)
	}

	result := `// Code generated by github.com/mrsinham/zerogen. DO NOT EDIT.
package compositionexternal

func (b *base) Reset() {
	b.field1 = ""
	b.Field1 = ""
}
`
	if b.String() != result {
		t.Fatalf("result is not the same as expected : got \n%q \n expected  \n%q", b.String(), result)
	}

}

func TestCompositionExternalNotExported(t *testing.T) {

	pkg := "github.com/mrsinham/zerogen/test/compositionexternal"
	structure := "compositionNotExported"
	write := false
	b := &bytes.Buffer{}
	if err := parsePackage(&pkg, &structure, &write, b); err != nil {
		t.Fatal(err)
	}

	result := `// Code generated by github.com/mrsinham/zerogen. DO NOT EDIT.
package compositionexternal

import sub "github.com/mrsinham/zerogen/test/compositionexternal/sub"

func (c *compositionNotExported) Reset() {
	c.field1 = ""
	c.Sub2 = sub.Sub2{}
}
`
	if b.String() != result {
		t.Fatalf("result is not the same as expected : got \n%q \n expected  \n%q", b.String(), result)
	}

}
