// Code generated by github.com/mrsinham/zerogen. DO NOT EDIT.
package structnoname

import http "net/http"

func (s *structnoname) Reset() {
	s.field1 = 0
	s.field2 = struct {
		tutu1 *http.Request
		tutu2 *http.Request
		tutu3 struct {
			file string
		}
	}{}
}
